application: free-proxy-list
version: 1
runtime: go
api_version: go1

handlers:
- url: /(.*\.(gif|png|jpg|ico))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$


- url: /.*
  script: _go_app
